Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false

AllCops:
  Exclude:
    - 'Guardfile'
    - 'Gemfile'
